### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-3yia1#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by codeyourfaceoff** [comment]
Was able to reproduce the issue by:

1. Creating a new item
2. Purposely not inputting an image url in the form
3. Submitting the form

<img width="942" alt="Creating the item without an image" src="https://user-images.githubusercontent.com/31673840/196021629-7c456721-c41d-4dc4-815b-a6b849d879ba.png">

<img width="1136" alt="The item after creation with broken image url" src="https://user-images.githubusercontent.com/31673840/196021591-594fe713-833f-42bc-aa70-1f5cd9b3df14.png">
